arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - arm_joint
       - hand_joint
       
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_link: {trajectory: 0.1, goal: 0.1}
      hand_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
/gazebo_ros_control:
    pid_gains:
      arm_joint: {p: 1000.0, i: 100.0, d: 10.0}
      hand_joint: {p: 1000.0, i: 100.0, d: 10.0}

      